[package]
name = "bedrock-rs-md-venue"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "bedrock_rs_md_venue"
path = "src/lib.rs"

[dependencies]
bedrock-rs-common = { path = "../bedrock-rs-common" }
bedrock-rs-md = { path = "../bedrock-rs-md" }
serde_json = "1"
