[package]
name = "bedrock-rs-replay"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "bedrock_rs_replay"
path = "src/lib.rs"

[dependencies]
bedrock-rs-common = { path = "../bedrock-rs-common" }
bedrock-rs-md = { path = "../bedrock-rs-md" }

